### ISSUE TITLE
Update Unlock price infographic

### ISSUE THREAD

**Issue by derkrasseleo** [DangerAspect/siege#19]
I think [the infographic on your website](https://siege.dangeraspect.xyz/assets/images/operator-prices/OperatorPrices-Y5S4.jpg) is outdated and should contain the new operators and updated prices

**Comment by joeyfoo** [comment]
Hi, the infographic is indeed out of date. I do not intend to start updating it again; the Discord currently uses a text version as an alternative.

**Comment by derkrasseleo** [comment]
Could you maybe give me a link to that file? I need it for a project,,
