### ISSUE TITLE
Y4S4 map is out of date with newest patch.

### ISSUE THREAD

**Issue by Codingale** [DangerAspect/siege#8]
Your infographics are out of date but the command is still linked in the discord.
Can you update this thanks. <3

Link for those on mobile etc: http://rainbow6.com/quickmatchrotation (your link is a bit bork because there's no space)

**Comment by joeyfoo** [comment]
I intend to! Just been really busy recently. You can find the latest at http://rainbow6.com/quickmatchrotation in the meantime.
________________________________

**Comment by joeyfoo** [comment]
Fixed in commit 4fd1787. You can find it online at https://siege.dangeraspect.xyz/infographics
